function cAsc = b8_charpoly_coeffs_normalized(W3,W4,W5,W6,W7)
%B8_CHARPOLY_COEFFS_NORMALIZED Normalized B8 characteristic polynomial.
%
% The coefficients are generated by differentiating the recurrence-based B8
% closing moment with forward sensitivities.  No finite-difference state
% perturbations are used.

[W8,info] = b8_closing_moment_normalized(W3,W4,W5,W6,W7);
g = info.gradW8(:);  % dW8/d[W3,W4,W5,W6,W7]

W = [1;0;1;W3;W4;W5;W6;W7];
d = zeros(8,1);

for ell = 0:7
    dWnorm = zeros(5,1);
    for j = 3:7
        Wj = W(j+1);
        Wjm1 = W(j);
        val = 0;
        if ell == j
            val = val + 1;
        end
        if ell == 0
            val = val + (j/2 - 1)*Wj;
        elseif ell == 1
            val = val - j*Wjm1;
        elseif ell == 2
            val = val - (j/2)*Wj;
        end
        dWnorm(j-2) = val;
    end

    dW8Raw = g.'*dWnorm;
    if ell == 0
        dW8Raw = dW8Raw - 3*W8;
    elseif ell == 1
        dW8Raw = dW8Raw + 8*W7;
    elseif ell == 2
        dW8Raw = dW8Raw + 4*W8;
    end
    d(ell+1) = dW8Raw;
end

% p(lambda)=lambda^8-d7 lambda^7-...-d0.
cAsc = [-d(:); 1];
end
